name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        python-version: [3.6, 3.7, 3.8]

    steps:
      - name: Checking out repo
        uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.container[1] }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: set LOGGING_CONF_FILE env
        run: |
          export LOGGING_CONF_FILE=$(pwd)/sample_logging.conf
          echo $LOGGING_CONF_FILE

      - name: Install dependencies
        run: |
          pip install --upgrade pip setuptools
          pip install .[test]

      - name: Check if pylint is happy
        run: pylint transform_field

      - name: Run Unit Tests with min coverage of 60%
        run: pytest --cov=transform_field --cov-fail-under=60 -v tests/unit

      - name: Run Integration Tests with min coverage of 71%
        run: pytest --cov-fail-under=71 -v tests/integration
